name: Playwright CI with Docker + Allure

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests in Docker
        run: |
          docker build --no-cache -t playwright-ci .
          docker run --rm playwright-ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean -o allure-report


      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report